fun main() {
    val tokens = Lexer.Tokenizer("sin(3.14159)+(abc-6)^3/5+sqrt(3--2/2)")
    println(Calculator("sin(3.14159)+(abc-6)^3/5+sqrt(3--2/2)", Pair("abc", 1.0)))
    println(" --------- ")
    printTokens(tokens)
    println(" --- ")
    val concat = Lexer.TokenConcat(tokens)
    printTokens(concat)
    println(" --- ")
    val ec = Lexer.ExprConcat(concat)
    printTokens(ec)
    println(" --------- ")
    val sorted = Parser.TokenSorter(ec)
    printTokens(sorted)
    println(" --- ")
    val tree = Parser.TokenParser(sorted)
    printTree(tree)
    println(" --------- ")
    println(Calculator(tree, Pair("abc", 1.0)))
    println(" --------- ")
    val dep = Decompiler.DeParser(tree)
    printTokens(dep)
    println(" --- ")
    val del = Decompiler.DeLexer(dep)
    println(del)
}